require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/departure_dates", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # DepartureDate. As you add validations to DepartureDate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DepartureDate.create! valid_attributes
      get departure_dates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      departure_date = DepartureDate.create! valid_attributes
      get departure_date_url(departure_date)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_departure_date_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      departure_date = DepartureDate.create! valid_attributes
      get edit_departure_date_url(departure_date)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DepartureDate" do
        expect {
          post departure_dates_url, params: { departure_date: valid_attributes }
        }.to change(DepartureDate, :count).by(1)
      end

      it "redirects to the created departure_date" do
        post departure_dates_url, params: { departure_date: valid_attributes }
        expect(response).to redirect_to(departure_date_url(DepartureDate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DepartureDate" do
        expect {
          post departure_dates_url, params: { departure_date: invalid_attributes }
        }.to change(DepartureDate, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post departure_dates_url, params: { departure_date: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested departure_date" do
        departure_date = DepartureDate.create! valid_attributes
        patch departure_date_url(departure_date), params: { departure_date: new_attributes }
        departure_date.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the departure_date" do
        departure_date = DepartureDate.create! valid_attributes
        patch departure_date_url(departure_date), params: { departure_date: new_attributes }
        departure_date.reload
        expect(response).to redirect_to(departure_date_url(departure_date))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        departure_date = DepartureDate.create! valid_attributes
        patch departure_date_url(departure_date), params: { departure_date: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested departure_date" do
      departure_date = DepartureDate.create! valid_attributes
      expect {
        delete departure_date_url(departure_date)
      }.to change(DepartureDate, :count).by(-1)
    end

    it "redirects to the departure_dates list" do
      departure_date = DepartureDate.create! valid_attributes
      delete departure_date_url(departure_date)
      expect(response).to redirect_to(departure_dates_url)
    end
  end
end
